### PR TITLE
Revamping the host filtering for client api insertion

### PR DESCRIPTION
**Pull request by dysbulic**
#577 meant that you couldn't run a HTTP development server except on port 80 (and HTTPS on 443).

This patch changes the validity regex when adding domain filters. That filter is now `[*.]host.name.tld[:port]`.

It also appends the port if necessary when generating what the regex is matched against to grant access.

Additionally, it makes the `*.` wildcard optional which allows people to reduce exposure.

Still to be done is updating the translations. The wildcard pattern is now optional, so it not being present doesn't invalidate the input.

### CODE REVIEW

**Comment by toberndo** [comment]
This looks great! I appreciate the unit tests. Also support for double dash domains is nice. Merged to dev branch 👍

**Comment by toberndo** [comment]
I discovered a problem with ports in match patterns. We have this function to inject the content scripts into tabs in the browser that are already open when the extension gets installed or reloaded: https://github.com/mailvelope/mailvelope/blob/master/src/lib/inject.js#L80
The chrome.tabs.query method does not support port numbers in match patterns. Seems like for Firefox there is a way to support port numbers: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns
I made a fix in this branch: https://github.com/mailvelope/mailvelope/tree/host-port-number
But overall feels like this requires some more testing.

**Comment by dysbulic** [comment]
I didn't know about the insertion for already open windows. I'll look into it.

I'll try to figure out how to do more end-to-end testing…

**Comment by dysbulic** [comment]
I'm a bit stymied on this. Mocks aren't being inserted as I expect them to, and I'm running in circles trying to figure out why.

All that I really want is an end-to-end integration test where I specify a watchlist and then check if `mailvelope` was inserted or not, and some analogue of that for the tab insertion.

Most of my testing background is in `rspec` for ruby and I'm just getting the hang of these javascript tools. The existing test suite is no joke in terms of complexity.

**Comment by toberndo** [comment]
I tested again and then also released this feature with v4.3.2.

The only testing we have that is a bit going in the direction of end-to-end testing is described in https://github.com/mailvelope/mailvelope/pull/686.
But I can imagine that it's quite some effort if you want to simulate the content script injection.
Previous attempts to build up end-to-end testing have been abandoned: https://github.com/mailvelope/mailvelope-selenium
I feel like if the complexity of the test exceeds a certain limit then it's hard to maintain that over time.

**Pull request closed without merging**
