### PR TITLE
Add title to popup window

### PR DESCRIPTION
**Pull request by rugk**
Not tested, but it should work
Fixes https://github.com/mailvelope/mailvelope/issues/354

### CODE REVIEW

**Comment by toberndo** [comment]
Not working in Firefox for me :-(

**Comment by rugk** [comment]
Travis also shows an error, but this does not seem to be related to this PR...
> This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
>If you require sudo, add 'sudo: required' to your .travis.yml
>See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

**Comment by toberndo** [comment]
Looks like Travis is currently broken for Mailvelope pull requests.

**Comment by rugk** [comment]
Any other ideas?

**Comment by toberndo** [comment]
Current status: title set in editor, works in Chrome, but in in Firefox the moz-extension URL is displayed before the title.

**Pull request closed without merging**
