### PR TITLE
Confirmation when users close tab

### PR DESCRIPTION
**Pull request by c8k**
Added some methods to check if the user entered text in the textarea (e.g. when writing an email) or entered at least one recipient. If that is the case and the user tries to close the tab a confirmation dialog of the browser will be shown to prevent that the user looses his work.

I used the variable usedInputs in utils.js to save the input elements or the id of the component but I'm not sure if that's the best place.

Solves #232

### CODE REVIEW

**Comment by toberndo** [comment]
I think this feature would be great to have. Probably could be implemented in more straight forward way: you have state.plaintext and state.recipients already in the editor to check if the user entered something. In componentWillMount and componentWillUnmount of the editor you can use addEventListener() and removeEventListener() to register a method handleBeforeUnload. Here you can check the state and check also if we are in standalone browser popup mode (state.embedded === false) and only then show a confirmation dialog.

**Comment by c8k** [comment]
Isn't it better to do it in PlainText.js because it is used when you compose a new email on the website of a provider AND when you go to "Encrypt" in Mailvelope and select "Do you also want to encrypt a text?" editor.js is only used in the first case.

**Comment by toberndo** [comment]
In general I think these kind of "Do you really want to...?" user interactions come with a price as they are annoying for the 95% case where we can assume that the user knows what to do. So I would use them only if they really have a major benefit. Normally we would be better served by using a kind of draft feature that allows the user to restore closed sessions. But closing the compose popup is a use case where this feature is helpful. The encrypt text feature in the app I would say not so much: here you rather copy/paste text, but composing longer texts here... well, not sure. And closing tab I would not see the same risk as closing popup.
For the case where we embed the editor in the host page via client-API I would not like to interfere with the outer page, therefore this feature should be deactivated here as well.

**Comment by c8k** [comment]
Is the compose popup not the same as the embedded editor in the host page? I thought they would be the same but I'm asking because you said that this feature would be helpful in the popup but should be deactivated in the embedded editor.

To be sure: You mean that the feature would make the most sense in this popup (here on mailbox.org?
screenshot_mailvelope

**Comment by toberndo** [comment]
> Is the compose popup not the same as the embedded editor in the host page?

Both is only one Mailvelope UI component implemented in src/components/editor

**Comment by c8k** [comment]
> I think this feature would be great to have. Probably could be implemented in more straight forward way: you have state.plaintext and state.recipients already in the editor to check if the user entered something. In componentWillMount and componentWillUnmount of the editor you can use addEventListener() and removeEventListener() to register a method handleBeforeUnload. Here you can check the state and check also if we are in standalone browser popup mode (state.embedded === false) and only then show a confirmation dialog.

I inserted the method componentWillUnmount (I didn't commit anything because I was just testing) and closed the popup but the method won't be called. I don't know why.

**Pull request closed without merging**
