### PR TITLE
add ownCloud Mail to default watchlist

### PR DESCRIPTION
**Pull request by jancborchardt**
@uggrock please check :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@toberndo so @uggrock and I experimented a bit and haven’t found a correct syntax for it. Do you have a clue?

**Comment by uggrock** [comment]
@jancborchardt, the solution does not seem to be so straightforward as proposed with this pull request. We have discussed some other possibilities with @toberndo and a solution will be implemented soon.

**Comment by jancborchardt** [comment]
@uggrock great stuff, thank you!

**Comment by jancborchardt** [comment]
@uggrock @toberndo any news by the way or any way we can help? We’ll release ownCloud Mail 0.1 on May 6 and it would be great to announce it with Mailvelope compatibility. :)

**Pull request closed without merging**
