### PR TITLE
Add "Search box" in select keys to encrypt message with

### PR DESCRIPTION
**Pull request by interference-security**
image

### CODE REVIEW

**Comment by toberndo** [comment]
Thanks for the pull request, nice feature. This is much easier to review now. What I have seen from your build in https://github.com/mailvelope/mailvelope/issues/348 is that the search box replaces the old selection. I think it would be good to have both options: the old behavior with the selection for quick access for users with small set of keys, and the new search feature.

**Comment by interference-security** [comment]
I am not sure why it says "All checks have failed". But the build and test of the extension/add-on did succeed.

**Comment by interference-security** [comment]
Nice idea toberndo. I will look into it.

**Comment by toberndo** [comment]
@interference-security Travis build is currently broken for all pull request. Your PR should be fine.

**Comment by interference-security** [comment]
@toberndo Select box with search feature added. It uses "select2" dependency.

**Comment by toberndo** [comment]
This looks amazingly simple from the code changes. Currently with Select2 if you click in the selection the dropdown menu is cropped at the bottom. Also in the old selection a large dropdown opens, the height even exceeds the popup window and makes it easy to select a value. In general I don't want the user experience of the current selection to decrease because of the search feature. So this needs some more optimizations.

**Comment by interference-security** [comment]
@toberndo Dropdown overflow from the screen should be fixed now. Let me know if anything else of concern is there.

**Comment by toberndo** [comment]
The key selection has now been replaced with a recipient tag input control in the editor.

**Pull request closed without merging**
