### PR TITLE
Add mail.riseup.net to watchlist

### PR DESCRIPTION
**Pull request by micah**

### CODE REVIEW

**Comment by toberndo** [comment]
Is there any reference that riseup.net mail supports the Mailvelope client-API?

**Comment by micah** [comment]
Our webmail uses roundcube with the built-in Mailvelope support. Does that not provide the client API? If not, can you point me to what is needed to provide that?

**Comment by toberndo** [comment]
That's right, Roundcube supports the Mailvelope client-API. If you have tested it with activated API flag and it works then everything ok.

**Comment by micah** [comment]
Yes, we've tested it with the activated API flag and it works.

**Comment by toberndo** [comment]
Merged to dev branch

**Pull request closed without merging**
